export const DRAW_STATUS_COLORS = {
  upcoming: 'bg-blue-500 bg-opacity-20 text-blue-400 border-blue-500',
  active: 'bg-green-500 bg-opacity-20 text-green-400 border-green-500',
  completed: 'bg-yellow-500 bg-opacity-20 text-yellow-400 border-yellow-500',
  cancelled: 'bg-red-500 bg-opacity-20 text-red-400 border-red-500',
} as const;

export const PRIZE_TYPES = {
  physical: {
    icon: '📦',
    label: 'Physical Prize',
    color: 'text-blue-400',
  },
  digital: {
    icon: '💎',
    label: 'Digital Prize',
    color: 'text-purple-400',
  },
} as const;

export const MOCK_DRAWS = [
  {
    drawId: '1',
    organizerId: 'org1',
    title: 'Golden NFT Collection Giveaway',
    description: 'Win exclusive golden NFTs from our premium collection',
    startTime: new Date('2024-01-15T10:00:00Z'),
    endTime: new Date('2024-01-22T23:59:59Z'),
    status: 'active' as const,
    prizeIds: ['prize1', 'prize2'],
    winnerAddresses: [],
    participantCount: 1247,
    maxParticipants: 5000,
  },
  {
    drawId: '2',
    organizerId: 'org2',
    title: 'Premium Hardware Bundle',
    description: 'Latest tech hardware including laptops and accessories',
    startTime: new Date('2024-01-20T10:00:00Z'),
    endTime: new Date('2024-01-27T23:59:59Z'),
    status: 'upcoming' as const,
    prizeIds: ['prize3'],
    winnerAddresses: [],
    participantCount: 0,
    maxParticipants: 1000,
  },
  {
    drawId: '3',
    organizerId: 'org1',
    title: 'Crypto Rewards Draw',
    description: 'Win ETH and Base tokens in this exclusive draw',
    startTime: new Date('2024-01-01T10:00:00Z'),
    endTime: new Date('2024-01-08T23:59:59Z'),
    status: 'completed' as const,
    prizeIds: ['prize4'],
    winnerAddresses: ['0x1234...5678'],
    participantCount: 3456,
    maxParticipants: 3456,
  },
];

export const MOCK_PRIZES = [
  {
    prizeId: 'prize1',
    drawId: '1',
    name: 'Golden Dragon NFT',
    description: 'Rare golden dragon NFT with special utilities',
    type: 'digital' as const,
    value: 0.5,
    distributionStatus: 'pending' as const,
    nftContractAddress: '0xabc...def',
    chain: 'base',
    imageUrl: '/api/placeholder/300/300',
  },
  {
    prizeId: 'prize2',
    drawId: '1',
    name: 'Premium Membership Token',
    description: 'Access token for premium platform features',
    type: 'digital' as const,
    value: 0.2,
    distributionStatus: 'pending' as const,
    nftContractAddress: '0x123...456',
    chain: 'base',
    imageUrl: '/api/placeholder/300/300',
  },
  {
    prizeId: 'prize3',
    drawId: '2',
    name: 'MacBook Pro M3',
    description: '16-inch MacBook Pro with M3 chip and 32GB RAM',
    type: 'physical' as const,
    value: 2500,
    distributionStatus: 'pending' as const,
    supplierId: 'supplier1',
    imageUrl: '/api/placeholder/300/300',
  },
  {
    prizeId: 'prize4',
    drawId: '3',
    name: '1 ETH Prize Pool',
    description: 'Winner receives 1 ETH directly to their wallet',
    type: 'digital' as const,
    value: 1,
    distributionStatus: 'distributed' as const,
    chain: 'base',
    imageUrl: '/api/placeholder/300/300',
  },
];
